// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideContainer: typeof import('./src/components/layout-aside/asideContainer.vue')['default']
    AsideInfo: typeof import('./src/components/layout-aside/asideInfo.vue')['default']
    AsideTitle: typeof import('./src/components/layout-aside/asideTitle.vue')['default']
    BlogContainer: typeof import('./src/components/blog-container/blogContainer.vue')['default']
    BlogContainerMain: typeof import('./src/components/blog-container/blogContainerMain.vue')['default']
    BlogFooter: typeof import('./src/components/layout-footer/blogFooter.vue')['default']
    BlogLayout: typeof import('./src/components/blogLayout.vue')['default']
    BlogTitle: typeof import('./src/components/layout-title/blogTitle.vue')['default']
    CodeImge: typeof import('./src/components/VerCode/codeImge.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBar: typeof import('./src/components/layout-header/headerBar.vue')['default']
    Layout: typeof import('./src/components/layout-container/layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBox: typeof import('./src/components/layout-header/topBox.vue')['default']
    TopSeacrchInput: typeof import('./src/components/layout-header/topSeacrchInput.vue')['default']
  }
}
